### ISSUE TITLE
Could a new feature be implemented to work with the discord party plugin?

### ISSUE THREAD

**Issue by tylersfd2** [InfernoStats/Nylo-Death-Indicators#1]
I don't know if that's against the game rules but would be nice to have nylos disappear for others in the discord party.

**Comment by nbulischeck** [comment]
I'm not sure what you mean. This plugin already does that for RuneLite party members.

**Comment by tylersfd2** [comment]
> nbulischeck

ah, your right. I haven't tried it in a party yet. Just looked at the code and see it has the party integration. Awesome!
