### ISSUE TITLE
Boulders at baba

### ISSUE THREAD

**Issue by StephanBijzitter** [InfernoStats/Nylo-Death-Indicators#10]
Having the boulders disappear upon xp-drop would allow for more consistent boulder skipping when not everyone in ToA is as experienced with it.

Seeing the functionality is pretty much the same as with nylo's I could probably fork this plugin and submit it to the plugin hub, but maybe you want to incorporate them into this plugin (and maybe make the plugin name more generic in the process), in which case that'd also be nice just because it'd be one fewer plugin to install.

Mostly just making this issue to see what you would want me to do

**Comment by InfernoStats** [comment]
Boulders disappearing upon xp drop would not be great because you can shoot them with a projectile that has a long delay and still get rolled tf out.

Another person is working on adding baba monkey waves and we'll rename this plugin, but I don't plan on accepting any other features.

**Comment by StephanBijzitter** [comment]
Oh that's a good point actually
