### ISSUE TITLE
Plugin makes hidden nylos reappear

### ISSUE THREAD

**Issue by Processhf** [InfernoStats/Nylo-Death-Indicators#2]
Currently I'm experiencing a bug where the Nylos are hidden before the projectile hits them (as intended), but then they reappear 1 tick later and display their full death animation unhidden.

**Comment by InfernoStats** [comment]
This was caused by a change in the NPC spawn/despawn code and now it appears that nylos "respawn" every single tick. I've pushed a fix for this and have requested a merge on the plugin-hub.

**Comment by JaccodR** [comment]
It still seems broken, any update on this?

**Comment by nbulischeck** [comment]
> It still seems broken, any update on this?

They haven't merged any plugin hub PRs for quite a while now.

**Comment by InfernoStats** [comment]
This was fixed by RL reverting the original change.
