### ISSUE TITLE
Add Accursed Sceptre to the Plugin

### ISSUE THREAD

**Issue by jrv123** [InfernoStats/Nylo-Death-Indicators#9]
The Accursed Sceptre behaves differently from other charged tridents such as a Sanguinesti Staff or Trident of the Swamp. The plugin will typically cause a nylocas to instantly become hidden upon a satisfactory xp drop that registers a kill. However, even with a satisfactory xp drop to kill, the plugin remains incompatible with the Accursed Sceptre and the nylos will remain completely visible. Please fix!

**Comment by InfernoStats** [comment]
Resolved by #11
